### PR TITLE
Update Privacy Policy

### PR DESCRIPTION
**Pull request by HenryHins**
- Remove Security Policy link
- Add email link

### CODE REVIEW

**Review by wparad — CHANGES_REQUESTED** [review]
I think the email for this whole document should just be privacy-policy@serify.org (there are two different emails in here already) and info@serify.org can be overloaded.  Forget filtering on the subject, changing the email address I think should cover us the best.

Thoughts?

**Comment by HenryHins** [comment]
I've asked Jason about this. He said it's okay to just use one email address. I'll make the changes tonight.

**Comment by wparad** [comment]
@HenryHins What do you think is the best thing to do here?

**Comment by HenryHins** [comment]
I think it is the best to take your adivce. I'll just use privacy-policy@serify.org in this page and I'll remove the sentence about filtering on the subject.

**Comment by wparad** [comment]
Sounds good, feel free to let me know when you disagree.

**Comment by HenryHins** [comment]
Cool I will. Right now I just think your way sounds better.

**Comment by wparad** [comment]
Issues will automatically close themselves if in the commit message you include "fixes #12"

**Pull request closed without merging**
