### PR TITLE
Build pull requests.

### PR DESCRIPTION
**Pull request by wparad**

### CODE REVIEW

**Review by HenryHins — APPROVED** [review]

**Comment by HenryHins** [comment]
I think I need write access in order to get this merged

**Comment by wparad** [comment]
I have been merging them so far, but normally the creator of the PR would do the merge.  I'll get you write access, and from now on you can merge your PRs.

It looks like you only approve one of the changes (strange, didn't even know you could do that.), but the whole PR is still outstanding.

**Comment by wparad** [comment]
In the future, PRs should be merged by the author of the PR just incase there are any followup actions required.  Don't sweat it for this one though

**Comment by HenryHins** [comment]
Okay. I merged this one because my other PRs didn't pass the CI check

**Pull request merged**
