### PR TITLE
Add contact button in footer in Login page. Fixes #2

### LINKED ISSUE #2: Create a "Contact' form for feeback.

### PR DESCRIPTION
**Pull request by HenryHins**
Added a "Contact Us" button in the footer in Login page. However sending an email requires server side processing so I'll leave that part for you.
Fixes #2

### CODE REVIEW

**Comment by wparad** [comment]
I'm thinking that while the link for `contact us` can be next to privacy policy.  Also something we have to consider is that the user may not actually be logged in.  Should we support that case as well?

**Comment by HenryHins** [comment]
The contact us button is bigger and taller than the privacy button, so it wouldn't look good next to the privacy button. Also when you're logged out, the contact form would reveal the "name" and "email" fields so no worries.

**Comment by wparad** [comment]
Got it, I think we need a better location for this button though.

My main concern right now, is that it looks weird being at the bottom like this, since it doesn't really match the rest of the footer.  What would work better is having it be a link like the privacy policy (i.e. the same style, etc...) and then either be a popout like the signin dialog, or a separate page altogether.

If we want to go with a button instead, I don't think the footer is the right place. As it is, we should improve the user experience.

Alternatively if you particularly thrilled with either of those, perhaps we should find another website which contains a feedback button in a way we want and copy that.  I think finding a good model to copy will ensure we have a good solution.

**Review by wparad — APPROVED** [review]
Fantastic, what do you think?  Do you like what we have now more or less than before?

**Comment by wparad** [comment]
Merging so that I can create the follow up PR.

**Comment by HenryHins** [comment]
I actually like the first one because I tend to not like popups. But it does look more straight forward to the users. We will probably redesign the whole website later on haha

**Comment by wparad** [comment]
not sure how this plays out on mobile, granted the popup may be a concern there, and we might need to go with something different entirely.

**Pull request merged**
