### PR TITLE
<Enter> clicks signin.

### PR DESCRIPTION
**Pull request by wparad**

### CODE REVIEW

**Review by HenryHins — CHANGES_REQUESTED** [review]
I tested it on some browsers. It works on Chrome on desktop, but it is still trying to signup user when I hit the enter key on Safari on desktop and iOS, and Chrome on iOS. I think this is a webkit browser issue.

**Comment by wparad** [comment]
I still can't believe there isn't a standacd way to do this.  I could add a
key event handler tied to the enter key.  Should i ddo that instead?

**Comment by HenryHins** [comment]
> I still can't believe there isn't a standacd way to do this.  I could add a
key event handler tied to the enter key.  Should i ddo that instead?

Yeah I think you could do that. As long as it works haha

**Comment by HenryHins** [comment]
It still doesn't work on webkit browsers. However, I've found a way to solve this problem. Do I make a new PR or can I update this one instead?

**Comment by wparad** [comment]
Just make a new one.  If you want either of the commits, you know how to
pull them in right?

**Comment by HenryHins** [comment]
I do but I don't need them for now

**Pull request closed without merging**
