### PR TITLE
Convert feedback form my jquery to angular. Fixes #2

### LINKED ISSUE #2: Create a "Contact' form for feeback.

### PR DESCRIPTION
**Pull request by wparad**

### CODE REVIEW

**Comment by HenryHins** [comment]
I'm curious why do we not use Bootstrap? We won't have to rewrite this when we switch from AngularJS to Vue.Js, and the animation looks a little weird now. We'll also need other features from Bootstrap like the hamburger button menu on the mobile nav bar

**Comment by HenryHins** [comment]
Also is it possible that the user gets a confirmation email that the feedback is received by us? That'd be really helpful

**Comment by wparad** [comment]
I can add in the user feedback email, although it wouldn't be in this repository.  For now I'm just saving these in a dynamoDB table.  I'll probably need to stick something on the admin screen at some point.

As far as your question about bootstrap, I am using it.  ui.bootstrap is bootstrap, but instead of hacking in jquery to get the functionality, it is written in pure angular so it matches the framework.  In general the use of bootstrap.js and jquery as dependency is a bad pattern.  It is much faster to manipulate the DOM via the virtual DOM in the framework language, as they are optimized for those changes.  In this case we want to have the same functionality but done using a pure bootstrap.js port to native framework, although not always does that exist.

When we switch to vue we would have to use the vue bootstrap (or something [like this](https://yuche.github.io/vue-strap/) or [this](http://morgul.github.io/vueboot/)) anyway so that doesn't save us anything.  Some of the attributes I removed might still have provided something, but I didn't spend too much time trying to figure out which ones worked with the library, especially since I want to move off this.

I'm a little concerned about the animation, as you pointed out, but I'm not exactly sure what is causing that problem.  I might investigate more later, but it wasn't the biggest problem, it seems like there is a css directive that is overriding our normal css.  I bet it is a small typo somewhere.

**Review by HenryHins — APPROVED** [review]

**Comment by wparad** [comment]
@HenryHins, I'm also not an expert of the integration of bootstrap with ui frameworks, if you find anything that recommends doing this a different way, let's investigate.

I know what's going on with the animation, :), but I'm not sure how to fix it :(.  The popup is overlaying the outside view, so it's removing the scroll bar.  That changes the width of the view, hence changing everything.  The best fix it probably to force the view to be height 100%, and have scrolling within the more specific elements, rather than scrolling on the outside div.

**Comment by wparad** [comment]
Also updated to improve the admin, and added the other developers as admin, so that everyone can test those screens (no reason to prevent this), but everyone should be careful navigating to there as there is no `Test` environment yet.  So changes on the admin screen will affect production (i.e. if you approve a verification it will actually get approved.)

**Pull request merged**
